//
//  DummyResponse.swift
//  LifeBloo
//
//  Created by Daniel Karsh on 6/3/17.
//  Copyright © 2017 Daniel Karsh. All rights reserved.
//

@testable import LifeModel
@testable import LifeViewModel

//let jsonResponse: [String: Any] = [
//    "page": 25,
//    "total_results": 19582,
//    "total_pages": 980,
//    "results": [[
//    "vote_count": 1481,
//    "id": 34544,
//    "video": false,
//    "vote_average": 6.2,
//    "title": "The A-Team",
//    "popularity": 4.233917,
//    "poster_path": "/eMwotYpkcE42lGlaoCpPFaolvst.jpg",
//    "original_language": "en",
//    "original_title": "The A-Team",
//    "genre_ids": [53, 28, 12, 35, 80],
//    "backdrop_path": "/rRBpKgStVlFlK0Rl42tqxNqX5E.jpg",
//    "adult": false,
//    "overview": "A group of Iraq War veterans goes on the run from U.S. military forces while they try to clear their names after being framed for a crime they didn't commit. Along the way, Col. Hannibal Smith, Capt. H.M. ‘Howling Mad’ Murdock , Sgt. Bosco ‘B.A.’ Baracus, and Lt. Templeton ‘Faceman’ Peck help out various people they encounter.",
//    "release_date": "2010-06-10"
//    ], [
//    "vote_count": 1414,
//    "id": 267860,
//    "video": false,
//    "vote_average": 5.7,
//    "title": "London Has Fallen",
//    "popularity": 4.233632,
//    "poster_path": "/9j2AmDhZvdwMyYKpqe4CtBkN1Tw.jpg",
//    "original_language": "en",
//    "original_title": "London Has Fallen",
//    "genre_ids": [28, 80, 53],
//    "backdrop_path": "/3JSakCxcM7mPDhLXCPH7jnwwbXy.jpg",
//    "adult": false,
//    "overview": "In London for the Prime Minister's funeral, Mike Banning discovers a plot to assassinate all the attending world leaders.",
//    "release_date": "2016-03-02"
//    ], [
//    "vote_count": 2696,
//    "id": 89,
//    "video": false,
//    "vote_average": 7.6,
//    "title": "Indiana Jones and the Last Crusade",
//    "popularity": 4.233445,
//    "poster_path": "/4p1N2Qrt8j0H8xMHMHvtRxv9weZ.jpg",
//    "original_language": "en",
//    "original_title": "Indiana Jones and the Last Crusade",
//    "genre_ids": [12, 28],
//    "backdrop_path": "/m3bEQlir8IWpmFocQBXWM5fkHri.jpg",
//    "adult": false,
//    "overview": "When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana must team up with Marcus Brody, Sallah and Elsa Schneider to follow in his father's footsteps and stop the Nazis from recovering the power of eternal life.",
//    "release_date": "1989-05-24"
//    ], [
//    "vote_count": 1918,
//    "id": 2105,
//    "video": false,
//    "vote_average": 6.4,
//    "title": "American Pie",
//    "popularity": 4.231243,
//    "poster_path": "/k40WFAXMRekWEqsjURO3jiWob67.jpg",
//    "original_language": "en",
//    "original_title": "American Pie",
//    "genre_ids": [35, 10749],
//    "backdrop_path": "/jlU4FvYxUXaxyYM0worlD7wHdQj.jpg",
//    "adult": false,
//    "overview": "At a high-school party, four friends find that losing their collective virginity isn't as easy as they had thought. But they still believe that they need to do so before college. To motivate themselves, they enter a pact to all "score." by their senior prom.",
//    "release_date": "1999-07-09"
//    ],[
//    "vote_count": 3293,
//    "id": 47964,
//    "video": false,
//    "vote_average": 5.2,
//    "title": "A Good Day to Die Hard",
//    "popularity": 4.228574,
//    "poster_path": "/c2SQMd00CCGTiDxGXVqA2J9lmzF.jpg",
//    "original_language": "en",
//    "original_title": "A Good Day to Die Hard",
//    "genre_ids": [28, 53],
//    "backdrop_path": "/17zArExB7ztm6fjUXZwQWgGMC9f.jpg",
//    "adult": false,
//    "overview": "Iconoclastic, take-no-prisoners cop John McClane, finds himself for the first time on foreign soil after traveling to Moscow to help his wayward son Jack - unaware that Jack is really a highly-trained CIA operative out to stop a nuclear weapons heist. With the Russian underworld in pursuit, and battling a countdown to war, the two McClanes discover that their opposing methods make them unstoppable heroes.",
//    "release_date": "2013-02-06"
//    ],[
//    "vote_count": 2095,
//    "id": 37686,
//    "video": false,
//    "vote_average": 6.6,
//    "title": "Super 8",
//    "popularity": 4.228486,
//    "poster_path": "/1JAKnHjENVz1adurNjtsWZnVQGY.jpg",
//    "original_language": "en",
//    "original_title": "Super 8",
//    "genre_ids": [53, 878, 9648],
//    "backdrop_path": "/9gh3kcihkCH5EWjxBtb19pdQxhm.jpg",
//    "adult": false,
//    "overview": "In 1979 Ohio, several youngsters are making a zombie movie with a Super-8 camera. In the midst of filming, the friends witness a horrifying train derailment and are lucky to escape with their lives. They soon discover that the catastrophe was no accident, as a series of unexplained events and disappearances soon follows. Deputy Jackson Lamb, the father of one of the kids, searches for the terrifying truth behind the crash.",
//    "release_date": "2011-06-08"
//    ],[
//    "vote_count": 1015,
//    "id": 88751,
//    "video": false,
//    "vote_average": 5.7,
//    "title": "Journey to the Center of the Earth",
//    "popularity": 4.22643,
//    "poster_path": "/nlYk34gpPfM6KFujxB9HTHZyeiL.jpg",
//    "original_language": "en",
//    "original_title": "Journey to the Center of the Earth",
//    "genre_ids": [28, 878, 12, 35, 10751],
//    "backdrop_path": "/tBMh4ig85nU6EC57pXhWfosSGlW.jpg",
//    "adult": false,
//    "overview": "On a quest to find out what happened to his missing brother, a scientist, his nephew and their mountain guide discover a fantastic and dangerous lost world in the center of the earth.",
//    "release_date": "2008-07-10"
//    ],[
//    "vote_count": 1732,
//    "id": 176,
//    "video": false,
//    "vote_average": 7.2,
//    "title": "Saw",
//    "popularity": 4.225243,
//    "poster_path": "/dHYvIgsax8ZFgkz1OslE4V6Pnf5.jpg",
//    "original_language": "en",
//    "original_title": "Saw",
//    "genre_ids": [27, 9648, 80],
//    "backdrop_path": "/fLL6WfUXvdQee1fD4xuzNnWfVBk.jpg",
//    "adult": false,
//    "overview": "Obsessed with teaching his victims the value of life, a deranged, sadistic serial killer abducts the morally wayward. Once captured, they must face impossible choices in a horrific game of survival. The victims must fight to win their lives back, or die trying...",
//    "release_date": "2004-10-01"
//    ],[
//    "vote_count": 2563,
//    "id": 146233,
//    "video": false,
//    "vote_average": 7.9,
//    "title": "Prisoners",
//    "popularity": 4.220851,
//    "poster_path": "/yAhqW57pwMAsCgmZpM5zSIVQVTh.jpg",
//    "original_language": "en",
//    "original_title": "Prisoners",
//    "genre_ids": [18, 53, 80],
//    "backdrop_path": "/cLGKawjQ5tUJCuDyR0OnGYT4fyf.jpg",
//    "adult": false,
//    "overview": "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts. But just how far will this desperate father go to protect his family?",
//    "release_date": "2013-09-18"
//    ],[
//    "vote_count": 1906,
//    "id": 290250,
//    "video": false,
//    "vote_average": 7,
//    "title": "The Nice Guys",
//    "popularity": 4.215583,
//    "poster_path": "/vNCeqxbKyDHL9LUza03V2Im16wB.jpg",
//    "original_language": "en",
//    "original_title": "The Nice Guys",
//    "genre_ids": [28, 35, 80, 9648, 53],
//    "backdrop_path": "/8GwMVfq8Hsq1EFbw2MYJgSCAckb.jpg",
//    "adult": false,
//    "overview": "A private eye investigates the apparent suicide of a fading porn star in 1970s Los Angeles and uncovers a conspiracy.",
//    "release_date": "2016-05-15"
//    ],[
//    "vote_count": 4,
//    "id": 290859,
//    "video": false,
//    "vote_average": 9.5,
//    "title": "Untitled Terminator Sequel",
//    "popularity": 4.214823,
//    "poster_path": null,
//    "original_language": "en",
//    "original_title": "Untitled Terminator Sequel",
//    "genre_ids": [878, 28],
//    "backdrop_path": null,
//    "adult": false,
//    "overview": "Sequel to James Cameron's films, and the final film in the franchise. 6th film in total.",
//    "release_date": ""
//    ],[
//    "vote_count": 33,
//    "id": 1631,
//    "video": false,
//    "vote_average": 5.4,
//    "title": "A Real Young Girl",
//    "popularity": 4.212874,
//    "poster_path": "/vmUxfIYlVzPBKIEvRcmqPzU6lB.jpg",
//    "original_language": "fr",
//    "original_title": "Une vraie jeune fille",
//    "genre_ids": [18],
//    "backdrop_path": "/3qFFHnFkULFJPY3ZRvRD0U2r6b8.jpg",
//    "adult": false,
//    "overview": "Bored and restless, Alice spends much of her time lusting after Jim, a local sawmill worker. When not lusting after him, Alice fills the hours with such pursuits as writing her name on a mirror with vaginal secretions and wandering the fields with her underwear around her ankles. And, in true teenaged tradition, she spends a lot of time writing in her diary.",
//    "release_date": "1976-01-01"
//    ],[
//    "vote_count": 2137,
//    "id": 65754,
//    "video": false,
//    "vote_average": 7.1,
//    "title": "The Girl with the Dragon Tattoo",
//    "popularity": 4.212004,
//    "poster_path": "/voxRWFTtagLiqnJQs9tWQLB0MN.jpg",
//    "original_language": "en",
//    "original_title": "The Girl with the Dragon Tattoo",
//    "genre_ids": [53, 80, 9648, 18],
//    "backdrop_path": "/1fk2xS5hRkblBuag5JXZkmE8pg6.jpg",
//    "adult": false,
//    "overview": "This English-language adaptation of the Swedish novel by Stieg Larsson follows a disgraced journalist, Mikael Blomkvist, as he investigates the disappearance of a weary patriarch's niece from 40 years ago. He is aided by the pierced, tattooed, punk computer hacker named Lisbeth Salander. As they work together in the investigation, Blomkvist and Salander uncover immense corruption beyond anything they have ever imagined.",
//    "release_date": "2011-12-14"
//    ],[
//    "vote_count": 1594,
//    "id": 128,
//    "video": false,
//    "vote_average": 8.1,
//    "title": "Princess Mononoke",
//    "popularity": 4.201429,
//    "poster_path": "/gzlJkVfWV5VEG5xK25cvFGJgkDz.jpg",
//    "original_language": "ja",
//    "original_title": "もののけ姫",
//    "genre_ids": [12, 14, 16],
//    "backdrop_path": "/dWAYPAKlJi0n85P0xVEvQ2FOYLF.jpg",
//    "adult": false,
//    "overview": "Ashitaka, a prince of the disappearing Ainu tribe, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
//    "release_date": "1997-07-12"
//    ],[
//    "vote_count": 4254,
//    "id": 14161,
//    "video": false,
//    "vote_average": 5.6,
//    "title": "2012",
//    "popularity": 4.193434,
//    "poster_path": "/5tIW9nTuxxy8iXSvsKJqFDVZpyg.jpg",
//    "original_language": "en",
//    "original_title": "2012",
//    "genre_ids": [28, 12, 878],
//    "backdrop_path": "/ywxrdkfbr8Dg3SBW2gi4kC59qOb.jpg",
//    "adult": false,
//    "overview": "Dr. Adrian Helmsley, part of a worldwide geophysical team investigating the effect on the earth of radiation from unprecedented solar storms, learns that the earth's core is heating up. He warns U.S. President Thomas Wilson that the crust of the earth is becoming unstable and that without proper preparations for saving a fraction of the world's population, the entire race is doomed. Meanwhile, writer Jackson Curtis stumbles on the same information. While the world's leaders race to build "arks" to escape the impending cataclysm, Curtis struggles to find a way to save his family. Meanwhile, volcanic eruptions and earthquakes of unprecedented strength wreak havoc around the world.",
//    "release_date": "2009-10-10"
//    ],[
//    "vote_count": 2190,
//    "id": 180,
//    "video": false,
//    "vote_average": 7,
//    "title": "Minority Report",
//    "popularity": 4.188018,
//    "poster_path": "/h3lpltSn7Rj1eYTPQO1lYGdw4Bz.jpg",
//    "original_language": "en",
//    "original_title": "Minority Report",
//    "genre_ids": [28, 53, 878, 9648],
//    "backdrop_path": "/pG39VS7fFLk2crzq57RkqDfUSk0.jpg",
//    "adult": false,
//    "overview": "John Anderton is a top 'Precrime' cop in the late-21st century, when technology can predict crimes before they're committed. But Anderton becomes the quarry when another investigator targets him for a murder charge.",
//    "release_date": "2002-06-20"
//    ],[
//    "vote_count": 1031,
//    "id": 296099,
//    "video": false,
//    "vote_average": 6.1,
//    "title": "Vacation",
//    "popularity": 4.18081,
//    "poster_path": "/q9kL9WW0Uu4AcfTi5iCLcYzBgnm.jpg",
//    "original_language": "en",
//    "original_title": "Vacation",
//    "genre_ids": [35],
//    "backdrop_path": "/3pDqidHzSDHDNlrZ6isAvXNFiYy.jpg",
//    "adult": false,
//    "overview": "Hoping to bring his family closer together and to recreate his childhood vacation for his own kids, a grown up Rusty Griswold takes his wife and their two sons on a cross-country road trip to the coolest theme park in America, Walley World. Needless to say, things don't go quite as planned.",
//    "release_date": "2015-07-28"
//    ],[
//    "vote_count": 1480,
//    "id": 1635,
//    "video": false,
//    "vote_average": 6.5,
//    "title": "The Island",
//    "popularity": 4.17931,
//    "poster_path": "/erprD7GIkvZz2KM4Z35eyTJKZMI.jpg",
//    "original_language": "en",
//    "original_title": "The Island",
//    "genre_ids": [28, 53, 878, 12],
//    "backdrop_path": "/7gckgf6lmlKsjtkmS8O0oT3iEev.jpg",
//    "adult": false,
//    "overview": "In 2019, Lincoln Six-Echo is a resident of a seemingly Utopian but contained facility. Like all of the inhabitants of this carefully-controlled environment, Lincoln hopes to be chosen to go to the 'The Island' – reportedly the last uncontaminated location on the planet. But Lincoln soon discovers that everything about his existence is a lie. He and all of the other inhabitants of the facility are actually human clones.",
//    "release_date": "2005-07-20"
//    ],[
//    "vote_count": 2967,
//    "id": 604,
//    "video": false,
//    "vote_average": 6.6,
//    "title": "The Matrix Reloaded",
//    "popularity": 4.166475,
//    "poster_path": "/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg",
//    "original_language": "en",
//    "original_title": "The Matrix Reloaded",
//    "genre_ids": [12, 28, 53, 878],
//    "backdrop_path": "/1jgulSytTJcATkGX8syGbD2glXD.jpg",
//    "adult": false,
//    "overview": "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
//    "release_date": "2003-05-15"
//    ],[
//    "vote_count": 1526,
//    "id": 107985,
//    "video": false,
//    "vote_average": 6.7,
//    "title": "The World's End",
//    "popularity": 4.162096,
//    "poster_path": "/9DBKqINsayQRZU0Ry0HFjeps5XJ.jpg",
//    "original_language": "en",
//    "original_title": "The World's End",
//    "genre_ids": [35, 28, 878],
//    "backdrop_path": "/uTODVVo2EDocnrtvdlOvQw1bO2R.jpg",
//    "adult": false,
//    "overview": "Five friends who reunite in an attempt to top their epic pub crawl from 20 years earlier unwittingly become humankind's only hope for survival.",
//    "release_date": "2013-07-18"
//    }]
//]


let dummyResponse: ResponsePopular = {
    let movie0 = MovieModel(
        poster_path: "/xbpSDU3p7YUGlu9Mr6Egg2Vweto.jpg",
        adult: false,
        overview: "Captain Jack Sparrow is",
        release_date: "2017-05-23",
        genre_ids: [28,12,35,14],
        id: 10000,
        original_title: "Pirates of the Caribbean: Dead Men Tell No Tales",
        original_language: "en",
        title: "Pirates of the Caribbean: Dead Men Tell No Tales",
        backdrop_path: "/3DVKG54lqYbdh8RNylXeCf4MBPw.jpg",
        popularity: 287.511631,
        vote_count: 645,
        video: false,
        vote_average: 6.6)
    let movie1 = MovieModel(
        poster_path: "/xbpSDU3p7YUGlu9Mr6Egg2Vweto.jpg",
        adult: false,
        overview: "ZZZZZ Captain Jack Sparrow is",
        release_date: "2017-05-23",
        genre_ids: [28,12,35,14],
        id: 10001,
        original_title: "Pirates of the Caribbean: Dead Men Tell No Tales",
        original_language: "en",
        title: "Pirates of the Caribbean: Dead Men Tell No Tales",
        backdrop_path: "/3DVKG54lqYbdh8RNylXeCf4MBPw.jpg",
        popularity: 287.511631,
        vote_count: 645,
        video: false,
        vote_average: 6.6)
    return ResponsePopular(page: 33, movies: [movie0,movie1], total_results: 1000000, total_pages: 1000)
}()

let image1x1: UIImage = {
    UIGraphicsBeginImageContextWithOptions(CGSize(width:1, height:1), true, 0)
    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    return image!
}()
